const config = {
	// 注册
	register: 'g1/user/register',
	// 短信验证码
	captcha: 'g1/system/sms/captcha',
	// 登录
	login: 'g1/user/login',
	// 忘记密码
	forgetPwd: 'g1/user/forgetPwd',
	// 首页信息
	desktop: 'p1/desktop/init',
	// 个人中心
	mine: 'p1/user/detail',
	// 修改用户信息
	changeUser: 'p1/user/changeUser',
	// 运动记录列表
	exerciseList: 'p1/exercise/list',
	// 添加运动记录
	addExercise: 'p1/exercise/add',
	// 获取血糖监测提醒
	glu: 'p1/monitor/glu',
	// 获取复查监测提醒
	review: 'p1/monitor/review',
	// 添加血糖监测提醒
	addGlu: 'p1/monitor/addGluMonitors',
	// 修改血糖监测提醒
	editGlu: 'p1/monitor/editGluMonitors',
	// 删除血糖提醒
	deleteGluMonitors: 'p1/monitor/deleteGluMonitors',
	// 添加复查监测提醒
	addReview: 'p1/monitor/addReviewMonitors',
	// 修改复查监测提醒
	editReview: 'p1/monitor/editReviewMonitors',
	// 删除复查提醒
	deleteReviewMonitors: 'p1/monitor/deleteReviewMonitors',
	// 修改检查提醒
	setMonitors: 'p1/monitor/setMonitors',
	// 添加血糖管理
	addGlus: 'p1/glu/addGlus',
	// 获取血糖记录列表
	getGlus: 'p1/glu/glurecords',
	// 获取血糖记录列表
	getGlusDaily: 'p1/glu/daily/list',
	// 获取个人档案
	detailEhr: 'p1/ehr/detail',
	// 添加个人档案
	addEhr: 'p1/ehr/addEhr',
	// 修改个人档案
	editEhr: 'p1/ehr/editEhr',
	// 获取站内信息
	getMessages: 'p1/message/getMessages',
	// 删除站内信息
	deleteMessages: 'p1/message/delete/',
	// 更改站内信息
	changeMessages: 'p1/message/change/',
	//添加身高记录
	addHeight: 'p1/height/addHeight',
	// 获取身高记录
	getHeight: 'p1/height/getHeight',
	// 获取身高记录曲线
	getHeightGraph: 'p1/height/getGraph',
	// 添加胰岛素治疗记录
	addInsList: 'p1/ins/add',
	// 获取胰岛素治疗记录
	getInsList: 'p1/ins/list',
	// 根据日期获取胰岛素治疗记录.
	dailyInsList: 'p1/ins/daily/list',
	// 根据日期获取运动记录
	sportDaily: 'p1/exercise/daily/list',
	// 根据日期获取胰岛素记录
	insDaily: 'p1/ins/daily/list',
	// 根据日期获取饮食记录
	dietsDaily: 'p1/diets/daily/list',
	// 获取小儿低GI食谱
	getLowRecipes: 'g1/food/getBooks',
	// 获取食谱详情
	getRecipesDetails: 'g1/food/getBook/',
	// 收藏食谱
	followFood: 'p1/favorites/',
	// 获取收藏食谱
	followList: 'p1/favorites/list',
	// 获取自定义食谱
	getMyBooks: 'p1/diets/getMyBooks',
	// 获取我的饮食记录
	getDiets: 'p1/diets/list',
	// 添加饮食记录
	addDiets: 'p1/diets/addDiets',
	// 获取食材
	getMaterials: 'g1/food/getMaterials',
	// 添加自定义食谱
	addMyBooks: 'p1/diets/addMyBooks',
	// 获取食材中的独立食材
	aloneGetBook: 'g1/food/getBook/materials/',
	// 获取单克食材能量
	aloneMaterials: 'g1/food/getBook/materials/alone/',
}

export default config;